#!/bin/sh
#
# Description: ENTRYPOINT for running Docker Images in Containers

# Use this file for customizing the default behavior when a container is created

set -e
printenv
 
cd /dotnetcorespa
if [ "$ASPNETCORE_ENVIRONMENT" = "Production" ]; then
    echo -e "\n\n\n...Static Kestrel server files /wwwroot/dist files:\n\n\n"
    cd wwwroot/dist && ls -l 
    # /dotnetcorespa/FlightSearch
    if [ -f ./log/stdout ]; then
        tail -f ./log/stdout;
    fi
    /dotnetcorespa/FlightSearch 
elif [ "$ASPNETCORE_ENVIRONMENT" = "Development" ]; then
    echo -e "\n\n\n...Launch Settings: \n\n\n" 
    cat /dotnetcorespa/Properties/launchSettings.json
    cat /dotnetcorespa/appsettings.json
    ## Create server configurations from .tpl files
    cd /dotnetcorespa/tpl
    sed -i "s/5000/${PORT}/g" launchSettings-local.json 
    sed -i "s/5001/${SSL_PORT}/g" launchSettings-local.json
    sed -i "s/5000/${PORT}/g" appsettings-local.json 
    sed -i "s/5001/${SSL_PORT}/g" appsettings-local.json
    cp launchSettings-local.json /dotnetcorespa/Properties/launchSettings.json
    cp appsettings-local.json /dotnetcorespa/appsettings.json
    echo "Node Version: " && node -v
    echo "NPM Version: " && npm -v
    cd /dotnetcorespa
    cp ./tpl/appsettings-local.json ./appsettings.Development.json 
    sed -i "s/\"Default\": \"Information\"/\"Default\": \"Debug\"/g" ./appsettings.Development.json
    sed -i "s/\"Microsoft\": \"Information\"/\"Microsoft\": \"Debug\"/g" ./appsettings.Development.json 
    echo ".NET SDK Version: " && dotnet --version
    echo -e "\n\n\n... Installing node project dependencies..."
	npm config set package-lock false
    npm install
    echo -e "\n\n\n... Packaging static files to server..."  
    node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --display detailed  
    node node_modules/webpack/bin/webpack.js --config webpack.config.js --display detailed  
    echo -e "\n\n\n... Starting the server..." 
    dotnet run -c Debug -r alpine.3.6-x64
fi



